(() => {
  "use strict";
  document.addEventListener("DOMContentLoaded", () => {
    if(!window.AYA)return;
    const cartRoot=document.querySelector("[data-cart-items]"); const subtotalNode=document.querySelector("[data-cart-subtotal]"); const draft=Object.assign({orderType:"personal",customer:{},shipping:{},notes:""},window.AYA.readDraft());
    const requestedType=new URLSearchParams(location.search).get("type"); if(["personal","business"].includes(requestedType))draft.orderType=requestedType;
    let stage=1;
    const renderCart=()=>{const items=window.AYA.cartDetails();subtotalNode.textContent=window.AYA.formatPrice(window.AYA.cartSubtotal());if(!items.length){cartRoot.innerHTML='<div class="empty-state"><strong>Keranjang masih kosong.</strong><p>Pilih produk dan varian sebelum melanjutkan pemesanan.</p><a class="button button-primary" href="products.html">Buka Katalog</a></div>';return;}cartRoot.innerHTML=items.map(({product,variant,quantity,subtotal})=>`<article class="cart-item"><img src="${window.AYA.escapeHTML(product.image||product.placeholder)}" alt="${window.AYA.escapeHTML(product.name)}" data-image-fallback="${window.AYA.escapeHTML(product.id)}"/><div class="cart-item-main"><span>${window.AYA.escapeHTML(product.line)}</span><h3>${window.AYA.escapeHTML(product.name)}</h3><label>Varian<select data-cart-variant="${window.AYA.escapeHTML(product.id)}" data-old-variant="${window.AYA.escapeHTML(variant.name)}">${product.variants.map((option)=>`<option ${option.name===variant.name?"selected":""}>${window.AYA.escapeHTML(option.name)}</option>`).join("")}</select></label><div class="cart-item-meta"><strong>${window.AYA.formatPrice(variant.price)}</strong><label>Jumlah<input type="number" min="${product.minQuantity||1}" value="${quantity}" data-cart-qty="${window.AYA.escapeHTML(product.id)}" data-variant="${window.AYA.escapeHTML(variant.name)}"/></label></div></div><div class="cart-item-side"><strong>${window.AYA.formatPrice(subtotal)}</strong><button type="button" data-cart-remove="${window.AYA.escapeHTML(product.id)}" data-variant="${window.AYA.escapeHTML(variant.name)}">Hapus</button></div></article>`).join("");};
    const invalidateTotal=()=>{draft.shipping.amount=null;draft.total=null;window.AYA.saveDraft(draft);document.querySelector("[data-summary-shipping]").textContent="Belum tersedia";document.querySelector("[data-summary-total]").textContent="Belum dapat dihitung";};
    cartRoot.addEventListener("change",(event)=>{const qty=event.target.closest("[data-cart-qty]");if(qty){window.AYA.updateCartItem(qty.dataset.cartQty,qty.dataset.variant,qty.value);invalidateTotal();renderCart();return;}const select=event.target.closest("[data-cart-variant]");if(select){const cart=window.AYA.getCart();const item=cart.find((entry)=>entry.productId===select.dataset.cartVariant&&entry.variantName===select.dataset.oldVariant);if(item){item.variantName=select.value;window.AYA.saveCart(cart);invalidateTotal();renderCart();}}});
    cartRoot.addEventListener("click",(event)=>{const button=event.target.closest("[data-cart-remove]");if(!button)return;window.AYA.removeCartItem(button.dataset.cartRemove,button.dataset.variant);invalidateTotal();renderCart();}); window.addEventListener("aya:cart-change",renderCart);
    const orderTypeInputs=[...document.querySelectorAll('[name="orderType"]')]; const personalFields=document.querySelector("[data-personal-fields]"); const businessFields=document.querySelector("[data-business-fields]");
    const setType=(type)=>{draft.orderType=type;orderTypeInputs.forEach((input)=>input.checked=input.value===type);personalFields.hidden=type!=="personal";businessFields.hidden=type!=="business";businessFields.querySelectorAll("input,select").forEach((input)=>input.required=type==="business"&&["organization","pic","businessWhatsapp","businessType"].includes(input.name));personalFields.querySelectorAll("input").forEach((input)=>input.required=type==="personal");invalidateTotal();}; orderTypeInputs.forEach((input)=>input.addEventListener("change",()=>setType(input.value))); setType(draft.orderType);
    const customerForm=document.querySelector("[data-customer-form]"); const shippingForm=document.querySelector("[data-shipping-form]"); const errors=document.querySelector("[data-order-errors]");
    const showErrors=(messages)=>{errors.hidden=!messages.length;errors.innerHTML=messages.length?`<strong>Periksa data berikut:</strong><ul>${messages.map((message)=>`<li>${window.AYA.escapeHTML(message)}</li>`).join("")}</ul>`:"";if(messages.length)errors.focus();};
    const customerData=()=>Object.fromEntries(new FormData(customerForm)); const shippingData=()=>Object.fromEntries(new FormData(shippingForm));
    const validateCustomer=()=>{const data=customerData();const messages=[];if(draft.orderType==="personal"){if(!data.customerName?.trim())messages.push("Nama lengkap wajib diisi.");if(!data.whatsapp?.trim())messages.push("Nomor WhatsApp wajib diisi.");}else{if(!data.organization?.trim())messages.push("Nama acara/usaha/perusahaan wajib diisi.");if(!data.pic?.trim())messages.push("Nama PIC wajib diisi.");if(!data.businessWhatsapp?.trim())messages.push("Nomor WhatsApp PIC wajib diisi.");if(!data.businessType)messages.push("Jenis kebutuhan wajib dipilih.");}if(!window.AYA.cartDetails().length)messages.push("Keranjang masih kosong.");showErrors(messages);if(!messages.length){draft.customer=data;draft.notes=data.notes||"";window.AYA.saveDraft(draft);}return !messages.length;};
    const validateShipping=()=>{const data=shippingData();const messages=[];if(!data.area?.trim())messages.push("Area atau kota wajib diisi.");if(!data.address?.trim())messages.push("Alamat atau detail lokasi wajib diisi.");showErrors(messages);if(!messages.length){draft.shipping={...data,amount:null,status:"integration-pending"};window.AYA.saveDraft(draft);}return !messages.length;};
    const go=(target,shouldScroll=true)=>{if(target===2&&stage===1&&!validateCustomer())return;if(target===3&&stage===2&&!validateShipping())return;if(target===3||target===4){renderReview();}stage=target;document.querySelectorAll("[data-stage]").forEach((node)=>{const active=Number(node.dataset.stage)===stage;node.hidden=!active;node.classList.toggle("active",active);});document.querySelectorAll("[data-stage-button]").forEach((button)=>button.classList.toggle("active",Number(button.dataset.stageButton)===stage));if(shouldScroll)document.querySelector(".gateway-panel")?.scrollIntoView({behavior:"smooth",block:"start"});}; document.querySelectorAll("[data-next-stage]").forEach((button)=>button.addEventListener("click",()=>go(Number(button.dataset.nextStage))));document.querySelectorAll("[data-prev-stage]").forEach((button)=>button.addEventListener("click",()=>go(Number(button.dataset.prevStage))));document.querySelectorAll("[data-stage-button]").forEach((button)=>button.addEventListener("click",()=>{const target=Number(button.dataset.stageButton);if(target<stage)go(target);}));
    const renderReview=()=>{const items=window.AYA.cartDetails();const customer=draft.customer||{};const shipping=draft.shipping||{};document.querySelector("[data-order-review]").innerHTML=`<div class="review-block"><strong>${draft.orderType==="business"?"Acara / Usaha":"Pesanan Pribadi"}</strong><p>${window.AYA.escapeHTML(draft.orderType==="business"?(customer.organization||""):(customer.customerName||""))}</p></div><div class="review-block"><strong>Produk</strong>${items.map((item)=>`<p>${window.AYA.escapeHTML(item.product.name)} · ${window.AYA.escapeHTML(item.variant.name)} × ${item.quantity}</p>`).join("")}</div><div class="review-block"><strong>Pengiriman</strong><p>${window.AYA.escapeHTML(shipping.area||"")} — ${window.AYA.escapeHTML(shipping.address||"")}</p></div>`;document.querySelector("[data-summary-subtotal]").textContent=window.AYA.formatPrice(window.AYA.cartSubtotal());document.querySelector("[data-summary-shipping]").textContent="Belum tersedia";document.querySelector("[data-summary-total]").textContent="Belum dapat dihitung";};
    document.querySelector("[data-whatsapp-support]")?.addEventListener("click",()=>{const items=window.AYA.cartDetails();const lines=["Halo AYA RAOS, saya membutuhkan bantuan untuk pesanan berikut:","",...items.map((item)=>`- ${item.product.name} | ${item.variant.name} | ${item.quantity} × ${window.AYA.formatPrice(item.variant.price)} = ${window.AYA.formatPrice(item.subtotal)}`),"",`Subtotal Produk: ${window.AYA.formatPrice(window.AYA.cartSubtotal())}`,"Ongkos kirim dan Total Pembayaran belum tersedia karena integrasi belum aktif."];window.AYA.openWhatsApp(lines.join("\n"));});
    renderCart();go(1,false);
  });
})();
