(() => {
  "use strict";
  document.addEventListener("DOMContentLoaded", () => {
    if (!window.AYA || !Array.isArray(window.AYA_PRODUCTS)) return;
    const products = window.AYA_PRODUCTS.filter((product) => product.visible);
    const grid = document.querySelector("[data-product-grid]"); const count = document.querySelector("[data-result-count]"); const pagination = document.querySelector("[data-pagination]"); const search = document.querySelector("[data-catalog-search]"); const sort = document.querySelector("[data-catalog-sort]"); const form = document.querySelector("[data-filter-form]");
    const state = { query:"", line:"", category:"", price:"", statuses:[], sort:"recommended", page:1, pageSize:8 };
    const params = new URLSearchParams(location.search); state.query = params.get("q") || ""; state.line = params.get("line") || ""; state.category = params.get("category") || ""; state.price = params.get("price") || ""; state.statuses = params.getAll("status"); state.sort = params.get("sort") || "recommended"; state.page = Math.max(1, Number(params.get("page")) || 1);
    search.value = state.query; sort.value = state.sort; form.querySelector(`[name="line"][value="${CSS.escape(state.line)}"]`)?.setAttribute("checked", "checked"); form.querySelector(`[name="price"][value="${CSS.escape(state.price)}"]`)?.setAttribute("checked", "checked"); state.statuses.forEach((value) => { const node = form.querySelector(`[name="status"][value="${CSS.escape(value)}"]`); if (node) node.checked = true; });
    const categories = [...new Set(products.map((product) => product.category))].sort(); document.querySelector("[data-category-options]").innerHTML = `<label><input type="radio" name="category" value="" ${!state.category ? "checked" : ""}/> Semua kategori</label>` + categories.map((category) => `<label><input type="radio" name="category" value="${window.AYA.escapeHTML(category)}" ${state.category === category ? "checked" : ""}/> ${window.AYA.escapeHTML(category)}</label>`).join("");
    const minPrice = (product) => Math.min(...product.variants.map((variant) => variant.price).filter(Number.isFinite), Infinity);
    const priceMatch = (price, filter) => !filter || (filter === "under50000" && price < 50000) || (filter === "50000-80000" && price >= 50000 && price <= 80000) || (filter === "over80000" && price > 80000);
    const syncURL = () => { const url = new URL(location.href); url.search = ""; if (state.query) url.searchParams.set("q", state.query); if (state.line) url.searchParams.set("line", state.line); if (state.category) url.searchParams.set("category", state.category); if (state.price) url.searchParams.set("price", state.price); state.statuses.forEach((value) => url.searchParams.append("status", value)); if (state.sort !== "recommended") url.searchParams.set("sort", state.sort); if (state.page > 1) url.searchParams.set("page", state.page); history.replaceState({}, "", url); };
    const filtered = () => { const query = state.query.trim().toLocaleLowerCase("id"); let list = products.filter((product) => { const searchable = [product.name, product.line, product.category, product.description, product.suitableUse].join(" ").toLocaleLowerCase("id"); return (!query || searchable.includes(query)) && (!state.line || product.lineKey === state.line) && (!state.category || product.category === state.category) && priceMatch(minPrice(product), state.price) && (!state.statuses.length || state.statuses.includes(product.status)); }); list.sort((a,b) => state.sort === "name-asc" ? a.name.localeCompare(b.name,"id") : state.sort === "price-asc" ? minPrice(a)-minPrice(b) : state.sort === "price-desc" ? minPrice(b)-minPrice(a) : a.priority-b.priority); return list; };
    const card = (product) => { const price = minPrice(product); const disabled = !product.orderable; return `<article class="product-card"><a class="product-card-image" href="product.html?id=${encodeURIComponent(product.id)}"><img src="${window.AYA.escapeHTML(product.image || product.placeholder)}" alt="${window.AYA.escapeHTML(product.name)}" loading="lazy" data-image-fallback="${window.AYA.escapeHTML(product.id)}"/><span class="status-badge status-${product.status}">${window.AYA.escapeHTML(product.publicStatus)}</span></a><div class="product-card-body"><span class="line-label line-${product.lineKey}">${window.AYA.escapeHTML(product.line)}</span><small>${window.AYA.escapeHTML(product.category)}</small><h2><a href="product.html?id=${encodeURIComponent(product.id)}">${window.AYA.escapeHTML(product.name)}</a></h2><p>${window.AYA.escapeHTML(product.description)}</p><div class="product-card-price"><span>${Number.isFinite(price) ? "Mulai" : "Harga"}</span><strong>${Number.isFinite(price) ? window.AYA.formatPrice(price) : "Belum tersedia"}</strong></div><div class="product-card-actions"><a class="button button-secondary" href="product.html?id=${encodeURIComponent(product.id)}">Detail</a><button class="button button-primary" type="button" data-quick-add="${window.AYA.escapeHTML(product.id)}" ${disabled ? "disabled" : ""}>${disabled ? "Belum Tersedia" : "Tambah"}</button></div></div></article>`; };
    const render = () => { const list = filtered(); const pages = Math.max(1, Math.ceil(list.length/state.pageSize)); state.page = Math.min(state.page,pages); const start = (state.page-1)*state.pageSize; const current = list.slice(start,start+state.pageSize); count.textContent = String(list.length); grid.innerHTML = current.length ? current.map(card).join("") : '<div class="empty-state catalog-empty"><strong>Produk tidak ditemukan.</strong><p>Ubah kata kunci atau reset filter untuk melihat pilihan lain.</p><button class="button button-secondary" type="button" data-empty-reset>Reset Filter</button></div>'; pagination.innerHTML = pages > 1 ? Array.from({length:pages},(_,i)=>`<button type="button" data-page="${i+1}" ${state.page===i+1?'aria-current="page"':''}>${i+1}</button>`).join("") : ""; syncURL(); };
    const readForm = () => { const data = new FormData(form); state.line = data.get("line") || ""; state.category = data.get("category") || ""; state.price = data.get("price") || ""; state.statuses = data.getAll("status"); state.page = 1; };
    let searchTimer; search.addEventListener("input", () => { clearTimeout(searchTimer); searchTimer = setTimeout(() => { state.query = search.value; state.page=1; render(); }, 180); }); sort.addEventListener("change", () => { state.sort=sort.value; state.page=1; render(); }); form.addEventListener("submit", (event) => { event.preventDefault(); readForm(); render(); document.querySelector("[data-filter-panel]")?.classList.remove("open"); }); form.addEventListener("reset", () => setTimeout(() => { state.query=""; search.value=""; state.sort="recommended"; sort.value="recommended"; state.line=state.category=state.price=""; state.statuses=[]; state.page=1; render(); },0)); pagination.addEventListener("click", (event) => { const button=event.target.closest("[data-page]"); if(!button)return; state.page=Number(button.dataset.page); render(); scrollTo({top:document.querySelector(".catalog-section").offsetTop-90,behavior:"smooth"}); }); grid.addEventListener("click", (event) => { if(event.target.closest("[data-empty-reset]")){form.reset();return;} const button=event.target.closest("[data-quick-add]"); if(!button)return; openVariant(button.dataset.quickAdd); });
    const panel=document.querySelector("[data-filter-panel]"); document.querySelector("[data-filter-open]")?.addEventListener("click",()=>panel?.classList.add("open")); document.querySelector("[data-filter-close]")?.addEventListener("click",()=>panel?.classList.remove("open"));
    const dialog=document.querySelector("[data-variant-dialog]"); const title=document.querySelector("[data-variant-title]"); const options=document.querySelector("[data-variant-options]"); const qty=document.querySelector("[data-variant-qty]"); let selected;
    function openVariant(id){ const product=window.AYA.getProduct(id); if(!product||!product.orderable)return; if(product.variants.length===1){window.AYA.addToCart(id,product.variants[0].name,product.minQuantity||1);return;} selected=product; title.textContent=product.name; qty.min=String(product.minQuantity||1); qty.value=String(product.minQuantity||1); options.innerHTML=product.variants.map((variant,index)=>`<label class="variant-option"><input type="radio" name="quickVariant" value="${window.AYA.escapeHTML(variant.name)}" ${index===0?"checked":""}/><span><strong>${window.AYA.escapeHTML(variant.name)}</strong><small>${window.AYA.formatPrice(variant.price)}</small></span></label>`).join(""); dialog.showModal(); }
    document.querySelector("[data-variant-form]")?.addEventListener("submit",(event)=>{ const submitter=event.submitter; if(submitter?.value==="cancel"||!selected)return; event.preventDefault(); const variant=new FormData(event.currentTarget).get("quickVariant"); window.AYA.addToCart(selected.id,variant,qty.value); dialog.close(); });
    render();
  });
})();
