(() => {
  "use strict";
  document.addEventListener("DOMContentLoaded",()=>{
    if(!window.AYA)return; const data=window.AYA_TESTIMONIALS||{}; const track=document.querySelector("[data-ticker-track]"); const featured=document.querySelector("[data-featured-testimonial]"); const texts=data.texts||[];
    if(track)track.innerHTML=texts.length?[...texts,...texts].map((item)=>`<article><span>“</span><blockquote>${window.AYA.escapeHTML(item.quote)}</blockquote><footer><strong>${window.AYA.escapeHTML(item.name)}</strong><small>${window.AYA.escapeHTML(item.meta||"")}</small></footer></article>`).join(""):'<div class="empty-state compact-state"><strong>Belum ada testimoni tulisan.</strong></div>';
    const item=(data.featured||[])[0]; if(featured)featured.innerHTML=item?`<img src="${window.AYA.escapeHTML(item.image)}" alt="Foto testimoni pelanggan AYA"/><div><span class="eyebrow">Testimoni Pilihan</span><blockquote>“${window.AYA.escapeHTML(item.quote)}”</blockquote><strong>${window.AYA.escapeHTML(item.name)}</strong><small>${window.AYA.escapeHTML(item.meta||"")}</small><button type="button" class="button button-secondary" data-open-featured>Lihat Foto</button></div>`:'<div class="empty-state"><strong>Foto testimoni belum tersedia.</strong></div>';
    const dialog=document.querySelector("[data-media-dialog]"); const content=document.querySelector("[data-dialog-content]");document.querySelector("[data-open-featured]")?.addEventListener("click",()=>{if(!item||!dialog||!content)return;content.innerHTML=`<img src="${window.AYA.escapeHTML(item.image)}" alt="Foto testimoni pelanggan AYA"/>`;dialog.showModal();});document.querySelector("[data-dialog-close]")?.addEventListener("click",()=>dialog?.close());dialog?.addEventListener("click",(event)=>{if(event.target===dialog)dialog.close();});
  });
})();
