function cancelVirtualReverse(fromProgress){animateVirtualReverse(fromProgress,0,()=>{const controller=pageFlip.getFlipController();const metrics=reverseEngineMetrics();setCoverageMode('current');syncTransitionIllusion(0);controller.fold(reversePoint(-metrics.w+2,metrics));reverseOriginalTurnNext=pageFlip.turnToNextPage;pageFlip.turnToNextPage=()=>{};reverseCancelPending=true;controller.stopMove()})}
function runVirtualReverseTap(){if(!prepareVirtualReverse())return;commitVirtualReverse(0)}
function prepareForward(){if(!pageFlip||currentPage>=sets[activeLine].length-1)return false;const r=bookWrap.getBoundingClientRect();const controller=pageFlip.getFlipController();const started=controller.start({x:r.width-2,y:edgeY(r.height)});if(!started)return false;forwardActive=true;forwardProgress=0;controller.fold({x:r.width-3,y:edgeY(r.height)});return true}
function forwardPoint(progress){const r=bookWrap.getBoundingClientRect();const p=Math.max(0,Math.min(1,progress));return{x:(r.width-2)-(2*r.width*p),y:edgeY(r.height)}}
function updateForward(raw,start){if(!forwardActive||!raw||!start)return;const travel=Math.max(0,start.x-raw.x);forwardProgress=Math.max(0,Math.min(1,travel/(raw.w*FORWARD_FULL_TRAVEL)));pageFlip.getFlipController().fold(forwardPoint(forwardProgress))}
function animateForward(from,to,onDone){cancelAnimationFrame(forwardRAF);const controller=pageFlip.getFlipController();const started=performance.now();const distance=Math.abs(to-from);const duration=Math.max(80,Math.min(190,220*distance));function frame(now){const t=Math.min(1,(now-started)/duration);const ease=1-Math.pow(1-t,3);forwardProgress=from+(to-from)*ease;controller.fold(forwardPoint(forwardProgress));if(t<1)forwardRAF=requestAnimationFrame(frame);else onDone?.()}forwardRAF=requestAnimationFrame(frame)}
function commitForward(){if(!forwardActive)return;const target=Math.max(.56,forwardProgress);animateForward(forwardProgress,target,()=>pageFlip.getFlipController().stopMove())}
function cancelForward(){if(!forwardActive)return;pageFlip.getFlipController().stopMove()}
function isBookControl(target){return !!target.closest('.control-shield,.variant-pop')}
bookWrap.addEventListener('pointerdown',e=>{if(!pageFlip||isBookControl(e.target))return;const raw=rawPagePoint(e.clientX,e.clientY);if(!raw)return;if(raw.x<0||raw.y<0||raw.x>raw.w||raw.y>raw.h)return;gestureAnchorSide=raw.x<raw.w*.25?'left':'right';gestureAnchorY=raw.y<raw.h*.50?'top':'bottom';variantPop.classList.remove('open');gestureActive=true;gestureDragging=false;gestureDirection=null;gesturePointerId=e.pointerId;gestureStartRaw=raw;gestureStartTime=performance.now();bookWrap.setPointerCapture?.(e.pointerId);e.preventDefault()},{passive:false});
bookWrap.addEventListener('pointermove',e=>{if(!gestureActive||e.pointerId!==gesturePointerId||!pageFlip||!gestureStartRaw)return;const raw=rawPagePoint(e.clientX,e.clientY);if(!raw)return;const dx=raw.x-gestureStartRaw.x,dy=raw.y-gestureStartRaw.y;if(!gestureDragging){if(Math.hypot(dx,dy)<DRAG_THRESHOLD)return;if(Math.abs(dx)<Math.abs(dy)*.35)return;gestureDirection=dx<0?'next':'prev';gestureAnchorSide=gestureDirection==='next'?'right':'left';if(gestureDirection==='prev'){if(!prepareVirtualReverse())return}else{if(!prepareForward())return}gestureDragging=true}if(gestureDirection==='prev')updateVirtualReverse(raw,gestureStartRaw);else updateForward(raw,gestureStartRaw);e.preventDefault()},{passive:false});
function finishGesture(e){if(!gestureActive||e.pointerId!==gesturePointerId||!pageFlip)return;const raw=rawPagePoint(e.clientX,e.clientY),start=gestureStartRaw,wasDrag=gestureDragging,direction=gestureDirection,elapsed=Math.max(1,performance.now()-gestureStartTime);gestureActive=false;gestureDragging=false;gestureDirection=null;gesturePointerId=null;gestureStartRaw=null;gestureStartTime=0;if(!raw||!start)return;if(wasDrag&&direction==='prev'){const travel=Math.max(0,raw.x-start.x),velocity=travel/elapsed,commit=travel>=raw.w*COMMIT_DISTANCE||(travel>=raw.w*FLICK_DISTANCE&&velocity>=FLICK_VELOCITY)||raw.x>=raw.w*.88;if(reverseActive){if(commit)commitVirtualReverse(reverseProgress);else cancelVirtualReverse(reverseProgress)}e.preventDefault();return}if(wasDrag&&direction==='next'){const travel=Math.max(0,start.x-raw.x),velocity=travel/elapsed,commit=travel>=raw.w*COMMIT_DISTANCE||(travel>=raw.w*FLICK_DISTANCE&&velocity>=FLICK_VELOCITY)||raw.x<=raw.w*.12;if(commit)commitForward();else cancelForward();e.preventDefault();return}const corner=raw.y<raw.h*.50?'top':'bottom';if(start.x<start.w*.25)runVirtualReverseTap();else pageFlip.flipNext(corner);e.preventDefault()}
bookWrap.addEventListener('pointerup',finishGesture,{passive:false});
bookWrap.addEventListener('pointercancel',e=>{if(!gestureActive||!pageFlip)return;if(reverseActive)cancelVirtualReverse(reverseProgress);else if(forwardActive)cancelForward();gestureActive=false;gestureDragging=false;gestureDirection=null;gesturePointerId=null;gestureStartRaw=null;gestureStartTime=0},{passive:false});
document.querySelectorAll('.ribbon').forEach(btn=>btn.addEventListener('click',()=>mountBook(btn.dataset.line)));
let resizeTimer;window.addEventListener('resize',()=>{clearTimeout(resizeTimer);resizeTimer=setTimeout(()=>mountBook(activeLine),120)});
requestAnimationFrame(()=>mountBook('spice'));
