const state={spice:sets.spice.map(()=>0),snacks:sets.snacks.map(()=>0),farm:sets.farm.map(()=>0)};
let activeLine='spice',currentPage=0,pageFlip=null,cartCount=0;
let reverseActive=false,reverseProgress=0,reversePrevIndex=-1,reverseOriginIndex=-1,reverseRAF=0,reverseCancelPending=false,reverseCommitPending=false,reverseOriginalTurnNext=null;
let reverseCoverage=null,coverageMode='current';
let forwardActive=false,forwardProgress=0,forwardRAF=0;
let gestureActive=false,gestureDragging=false,gestureDirection=null,gesturePointerId=null,gestureStartRaw=null,gestureStartTime=0,gestureAnchorY='top',gestureAnchorSide='right';
const book=document.getElementById('book'),bookWrap=document.getElementById('bookWrap'),bookUnderlay=document.getElementById('bookUnderlay'),variantPop=document.getElementById('variantPop'),variantHit=document.getElementById('variantHit'),cartHit=document.getElementById('cartHit'),count=document.getElementById('count');
const DRAG_THRESHOLD=2,COMMIT_DISTANCE=.24,FLICK_DISTANCE=.09,FLICK_VELOCITY=.18,FORWARD_FULL_TRAVEL=.70;
function money(n){return 'Rp'+new Intl.NumberFormat('id-ID').format(n)}
function productMarkup(p,line,index){const meta=lineMeta[line];const vi=state[line][index]||0;const v=p.variants[vi]||p.variants[0];const facts=[p.character?`<div class="fact"><b>KARAKTER</b><span>${p.character}</span></div>`:'',p.pairing?`<div class="fact"><b>COCOK</b><span>${p.pairing}</span></div>`:''].join('');const commerce=v?`<div class="page-commerce"><div><div class="variant-label">VARIAN</div><div class="variant"><span class="page-variant">${v[0]}</span>${p.variants.length>1?'<span class="chev">⌄</span>':''}</div></div><div class="price-cart"><div class="price page-price">${money(v[1])}</div><div class="cart page-cart">${CART_ICON}</div></div></div>`:`<div class="page-commerce unavailable-commerce"><div><div class="variant-label">STATUS</div><div class="variant status-only">${p.status||'Belum tersedia'}</div></div></div>`;return `<div class="leaf"><div class="photo"><img src="${p.image}" alt="${p.name}"></div><div class="line-signature"><img src="${meta.mark}" alt=""><span>${meta.title}</span></div><div class="content"><h1 class="product-title">${p.name}</h1><p class="lead">${p.lead}</p><div class="notes">${facts}</div>${commerce}</div></div>`}
function pageShell(p,line,index){return `<div class="page"><div class="page-inner">${productMarkup(p,line,index)}</div></div>`}
function updateBookmarks(){document.querySelectorAll('.ribbon').forEach(b=>b.classList.toggle('active',b.dataset.line===activeLine))}
function updateControlState(){const p=sets[activeLine][currentPage];const has=!!p?.variants?.length;variantHit.disabled=!has||p.variants.length<2;cartHit.disabled=!has;variantHit.setAttribute('aria-label',has&&p.variants.length>1?'Pilih varian':'Varian');cartHit.setAttribute('aria-label',has?'Tambah ke keranjang':'Produk tidak tersedia')}
function updateRenderedCommerce(){const p=sets[activeLine][currentPage];if(!p)return;const vi=state[activeLine][currentPage]||0;const v=p.variants[vi];if(v){document.querySelectorAll('#book .page').forEach((el,i)=>{if(i!==currentPage)return;el.querySelectorAll('.page-variant').forEach(n=>n.textContent=v[0]);el.querySelectorAll('.page-price').forEach(n=>n.textContent=money(v[1]));});}updateControlState()}
function buildVariantPop(){variantPop.innerHTML='';const p=sets[activeLine][currentPage];if(!p||p.variants.length<2){variantPop.classList.remove('open');return}p.variants.forEach((v,i)=>{const b=document.createElement('button');b.className='variant-opt'+(i===(state[activeLine][currentPage]||0)?' active':'');b.type='button';b.innerHTML=`<span>${v[0]}</span><span class="vprice">${money(v[1])}</span>`;b.addEventListener('pointerdown',e=>e.stopPropagation());b.addEventListener('click',e=>{e.stopPropagation();state[activeLine][currentPage]=i;variantPop.classList.remove('open');updateRenderedCommerce();buildVariantPop()});variantPop.appendChild(b)})}
[variantHit,cartHit].forEach(btn=>btn.addEventListener('pointerdown',e=>e.stopPropagation()));
variantHit.addEventListener('click',e=>{e.stopPropagation();if(variantHit.disabled)return;buildVariantPop();variantPop.classList.toggle('open')});
cartHit.addEventListener('click',e=>{e.stopPropagation();if(cartHit.disabled)return;cartCount++;count.textContent=cartCount;document.querySelectorAll('.page-cart').forEach(c=>{c.classList.add('done');setTimeout(()=>c.classList.remove('done'),600)})});
function renderUnderlay(){const arr=sets[activeLine];const next=currentPage<arr.length-1?currentPage+1:currentPage>0?currentPage-1:currentPage;const p=arr[next];bookUnderlay.innerHTML=p?`<div class="page-inner">${productMarkup(p,activeLine,next)}</div>`:''}
function resetForward(){cancelAnimationFrame(forwardRAF);forwardActive=false;forwardProgress=0}
function mountBook(line){activeLine=line;currentPage=0;reverseActive=false;resetForward();removeReverseCoverage();cancelAnimationFrame(reverseRAF);variantPop.classList.remove('open');if(pageFlip){try{pageFlip.destroy()}catch{}pageFlip=null}book.innerHTML=sets[line].map((p,i)=>pageShell(p,line,i)).join('');updateBookmarks();const r=bookWrap.getBoundingClientRect();pageFlip=new St.PageFlip(book,{width:Math.max(1,Math.round(r.width)),height:Math.max(1,Math.round(r.height)),size:'fixed',minWidth:Math.max(1,Math.round(r.width)),maxWidth:Math.max(1,Math.round(r.width)),minHeight:Math.max(1,Math.round(r.height)),maxHeight:Math.max(1,Math.round(r.height)),usePortrait:true,showCover:false,mobileScrollSupport:false,maxShadowOpacity:.30,flippingTime:500,useMouseEvents:false,clickEventForward:false,disableFlipByClick:true,showPageCorners:true,autoSize:false});pageFlip.loadFromHTML(document.querySelectorAll('#book .page'));pageFlip.on('flip',e=>{currentPage=e.data;renderUnderlay();updateRenderedCommerce();buildVariantPop()});pageFlip.on('changeState',e=>{if(e.data==='read'){resetForward();if(reverseCancelPending){reverseCancelPending=false;if(reverseOriginalTurnNext){pageFlip.turnToNextPage=reverseOriginalTurnNext;reverseOriginalTurnNext=null}removeReverseCoverage()}if(reverseCommitPending){reverseCommitPending=false;removeReverseCoverage()}reverseActive=false;reversePrevIndex=-1;reverseOriginIndex=-1;reverseProgress=0;renderUnderlay()}});requestAnimationFrame(()=>{renderUnderlay();updateRenderedCommerce();buildVariantPop()})}
