function rawPagePoint(clientX,clientY){const r=bookWrap.getBoundingClientRect();if(!r.width||!r.height)return null;return{x:clientX-r.left,y:clientY-r.top,w:r.width,h:r.height}}
function edgeY(h){return gestureAnchorY==='top'?2:h-2}
function reverseEngineMetrics(){const r=bookWrap.getBoundingClientRect();return{w:r.width,h:r.height,globalVisibleLeft:0}}
function reversePoint(localX,metrics){return{x:localX,y:edgeY(metrics.h)}}
function currentPageHTML(index=currentPage){const p=sets[activeLine][index];return p?`<div class="page-inner">${productMarkup(p,activeLine,index)}</div>`:''}
function ensureReverseCoverage(){if(reverseCoverage)return reverseCoverage;reverseCoverage=document.createElement('div');reverseCoverage.className='reverse-current-coverage current';document.querySelector('.stage').appendChild(reverseCoverage);return reverseCoverage}
function setCoverageMode(mode){coverageMode=mode;const c=ensureReverseCoverage();c.classList.toggle('current',mode==='current');c.classList.toggle('previous',mode==='previous');const idx=mode==='previous'?reversePrevIndex:reverseOriginIndex;c.innerHTML=currentPageHTML(idx)}
function syncTransitionIllusion(p){const c=reverseCoverage;if(!c)return;c.classList.toggle('transition-soft',p>.52&&p<.69)}
function syncOccludedCoverage(p){if(!reverseCoverage)return;if(p>=.60&&coverageMode!=='previous')setCoverageMode('previous');else if(p<=.54&&coverageMode!=='current')setCoverageMode('current');syncTransitionIllusion(p)}
function removeReverseCoverage(){if(reverseCoverage){reverseCoverage.remove();reverseCoverage=null}coverageMode='current'}
function prepareVirtualReverse(){if(!pageFlip||currentPage<=0)return false;reversePrevIndex=currentPage-1;reverseOriginIndex=currentPage;reverseProgress=0;setCoverageMode('current');const controller=pageFlip.getFlipController();const collection=pageFlip.getPageCollection();const metrics=reverseEngineMetrics();const originalSpread=collection.getCurrentSpreadIndex();const originalGetCurrent=pageFlip.getCurrentPageIndex;let started=false;try{collection.setCurrentSpreadIndex(reversePrevIndex);pageFlip.getCurrentPageIndex=()=>reversePrevIndex;started=controller.start({x:metrics.w-2,y:edgeY(metrics.h)})}finally{pageFlip.getCurrentPageIndex=originalGetCurrent;collection.setCurrentSpreadIndex(originalSpread)}if(!started){reversePrevIndex=-1;reverseOriginIndex=-1;reverseProgress=0;removeReverseCoverage();return false}controller.fold(reversePoint(-metrics.w+2,metrics));reverseActive=true;setTurning(true);return true}
function updateVirtualReverse(raw,start){if(!reverseActive||!raw||!start)return;const metrics=reverseEngineMetrics();const travel=Math.max(0,raw.x-start.x);reverseProgress=Math.max(0,Math.min(1,travel/(raw.w*.82)));syncOccludedCoverage(reverseProgress);const localX=-metrics.w+(2*metrics.w*reverseProgress);pageFlip.getFlipController().fold(reversePoint(localX,metrics))}
function animateVirtualReverse(from,to,onDone){cancelAnimationFrame(reverseRAF);const controller=pageFlip.getFlipController();const metrics=reverseEngineMetrics();const started=performance.now();const distance=Math.abs(to-from);const duration=Math.max(120,Math.min(360,(pageFlip.getSettings().flippingTime||500)*distance*.85));function frame(now){const t=Math.min(1,(now-started)/duration);const ease=1-Math.pow(1-t,3);reverseProgress=from+(to-from)*ease;syncOccludedCoverage(reverseProgress);const localX=-metrics.w+(2*metrics.w*reverseProgress);controller.fold(reversePoint(localX,metrics));if(t<1){reverseRAF=requestAnimationFrame(frame)}else if(onDone){onDone()}}reverseRAF=requestAnimationFrame(frame)}
function commitVirtualReverse(fromProgress){animateVirtualReverse(Math.max(.40,fromProgress),1,()=>{const collection=pageFlip.getPageCollection();const controller=pageFlip.getFlipController();const metrics=reverseEngineMetrics();setCoverageMode('previous');syncTransitionIllusion(1);currentPage=reversePrevIndex;collection.show(reversePrevIndex);renderUnderlay();updateRenderedCommerce();buildVariantPop();requestAnimationFrame(()=>requestAnimationFrame(removeReverseCoverage));controller.fold(reversePoint(metrics.w-2,metrics));reverseCommitPending=true;requestAnimationFrame(()=>controller.stopMove())})}
