let reverseCoverageCurrentTemplate=null,reverseCoveragePreviousTemplate=null;
function rawPagePoint(clientX,clientY){const r=bookWrap.getBoundingClientRect();if(!r.width||!r.height)return null;return{x:clientX-r.left,y:clientY-r.top,w:r.width,h:r.height}}
function edgeY(h){return gestureAnchorY==='top'?2:h-2}
function reverseEngineMetrics(){const rect=pageFlip.getRender().getRect();return{w:rect.pageWidth,h:rect.height,globalVisibleLeft:rect.left+rect.width/2}}
function reversePoint(localX,metrics){const margin=metrics.h/10;return{x:metrics.globalVisibleLeft+localX,y:gestureAnchorY==='top'?margin:metrics.h-margin}}
function currentPageHTML(index=currentPage){const p=sets[activeLine][index];return p?`<div class="page-inner">${productMarkup(p,activeLine,index)}</div>`:''}
function removeReverseCoverage(){if(reverseCoverage){reverseCoverage.remove();reverseCoverage=null}reverseCoverageCurrentTemplate=null;reverseCoveragePreviousTemplate=null;coverageMode='current'}
function createReverseCoverage(index){removeReverseCoverage();try{const source=pageFlip.getPage(index)?.getElement?.();const parent=source?.parentElement;if(!source||!parent)return null;const clone=source.cloneNode(true);clone.classList.add('reverse-current-coverage','current');clone.style.cssText=`display:block;position:absolute;inset:0;width:100%;height:100%;transform:none;transform-origin:0 0;clip-path:none;-webkit-clip-path:none;overflow:hidden;pointer-events:none;z-index:${pageFlip.getSettings().startZIndex+1};`;const currentInner=clone.querySelector?.('.page-inner');reverseCoverageCurrentTemplate=currentInner?.cloneNode(true)||null;const prevEl=pageFlip.getPage(index-1)?.getElement?.();const prevInner=prevEl?.querySelector?.('.page-inner');reverseCoveragePreviousTemplate=prevInner?.cloneNode(true)||null;parent.appendChild(clone);reverseCoverage=clone;coverageMode='current';return clone}catch{return null}}
function setCoverageMode(mode){if(!reverseCoverage||mode===coverageMode)return;const template=mode==='previous'?reverseCoveragePreviousTemplate:reverseCoverageCurrentTemplate;const currentInner=reverseCoverage.querySelector?.('.page-inner');if(!template||!currentInner)return;currentInner.replaceWith(template.cloneNode(true));reverseCoverage.classList.toggle('current',mode==='current');reverseCoverage.classList.toggle('previous',mode==='previous');coverageMode=mode}
function syncTransitionIllusion(p){if(!reverseCoverage)return;reverseCoverage.classList.toggle('transition-soft',p>.52&&p<.69)}
function syncOccludedCoverage(p){if(!reverseCoverage)return;if(p>=.60&&coverageMode!=='previous')setCoverageMode('previous');else if(p<=.54&&coverageMode!=='current')setCoverageMode('current');syncTransitionIllusion(p)}
function prepareVirtualReverse(){if(!pageFlip||currentPage<=0)return false;reversePrevIndex=currentPage-1;reverseOriginIndex=currentPage;reverseProgress=0;if(!createReverseCoverage(reverseOriginIndex))return false;const controller=pageFlip.getFlipController();const collection=pageFlip.getPageCollection();const metrics=reverseEngineMetrics();const originalSpread=collection.getCurrentSpreadIndex();const originalGetCurrent=pageFlip.getCurrentPageIndex;let started=false;try{collection.setCurrentSpreadIndex(reversePrevIndex);pageFlip.getCurrentPageIndex=()=>reversePrevIndex;started=controller.start({x:metrics.globalVisibleLeft+metrics.w-2,y:gestureAnchorY==='top'?2:metrics.h-2})}finally{pageFlip.getCurrentPageIndex=originalGetCurrent;collection.setCurrentSpreadIndex(originalSpread)}if(!started){reversePrevIndex=-1;reverseOriginIndex=-1;reverseProgress=0;removeReverseCoverage();return false}controller.fold(reversePoint(-metrics.w+2,metrics));reverseActive=true;setTurning(true);return true}
function updateVirtualReverse(raw,start){if(!reverseActive||!raw||!start)return;const metrics=reverseEngineMetrics();const travel=Math.max(0,raw.x-start.x);reverseProgress=Math.max(0,Math.min(1,travel/(raw.w*.92)));syncOccludedCoverage(reverseProgress);const localX=-metrics.w+(2*metrics.w*reverseProgress);pageFlip.getFlipController().fold(reversePoint(localX,metrics))}
function animateVirtualReverse(from,to,onDone){cancelAnimationFrame(reverseRAF);const controller=pageFlip.getFlipController();const metrics=reverseEngineMetrics();const started=performance.now();const distance=Math.abs(to-from);const duration=Math.max(140,Math.min(420,(pageFlip.getSettings().flippingTime||540)*distance*.92));function frame(now){const t=Math.min(1,(now-started)/duration);const ease=1-Math.pow(1-t,3);reverseProgress=from+(to-from)*ease;syncOccludedCoverage(reverseProgress);const localX=-metrics.w+(2*metrics.w*reverseProgress);controller.fold(reversePoint(localX,metrics));if(t<1)reverseRAF=requestAnimationFrame(frame);else onDone?.()}reverseRAF=requestAnimationFrame(frame)}
function commitVirtualReverse(fromProgress){animateVirtualReverse(Math.max(.46,fromProgress),1,()=>{const collection=pageFlip.getPageCollection();const controller=pageFlip.getFlipController();const metrics=reverseEngineMetrics();setCoverageMode('previous');syncTransitionIllusion(1);currentPage=reversePrevIndex;collection.show(reversePrevIndex);renderUnderlay();updateRenderedCommerce();buildVariantPop();requestAnimationFrame(()=>requestAnimationFrame(removeReverseCoverage));controller.fold(reversePoint(metrics.w-2,metrics));reverseCommitPending=true;requestAnimationFrame(()=>controller.stopMove())})}
