(() => {
  'use strict';
  const cfg=window.AYA_CONFIG?.supabase||{};
  const sb=window.supabase.createClient(cfg.url,cfg.publishableKey,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
  const state={session:null,functions:new Set(),page:'dashboard',products:[],variants:[],b2bConfig:[],measurements:[],testimonials:[],orders:[],cms:[],audit:[],roles:[],userRoles:[]};
  const pageEl=(n)=>document.querySelector(`[data-page="${n}"]`);
  const money=(n)=>n==null?'—':new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(Number(n));
  const esc=(v)=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
  const chip=(t,k='')=>`<span class="chip ${k}">${esc(t)}</span>`;
  const can=(f)=>state.functions.has(f);
  const q=async(table,select='*')=>{const {data,error}=await sb.from(table).select(select);if(error)throw error;return data||[]};
  const show=(msg,type='')=>{const e=document.getElementById('globalMessage');e.hidden=false;e.className=`message ${type}`;e.textContent=msg;setTimeout(()=>{e.hidden=true},5000)};
  const modal=(html)=>{document.getElementById('modalBody').innerHTML=html;document.getElementById('modal').showModal()};

  const nav=[
    ['dashboard','◈','Dashboard','dashboard.view'],['cms','▤','Website / CMS','website.view'],['products','◇','Product Master','product.view'],['b2c','▣','B2C Operations','b2c.view'],['b2b','⌁','B2B Operations','b2b.view'],['testimonials','✦','Testimonials','testimonial.view'],['finance','◎','Finance','finance.view'],['access','♙','Users & Access','users.access.view'],['audit','≡','Audit','audit.view'],['system','⚙','System','system.view']
  ];
  function renderNav(){const el=document.getElementById('nav');el.innerHTML=nav.filter(x=>can(x[3])).map(([id,ico,label])=>`<button data-go="${id}" class="${state.page===id?'active':''}"><span class="ico">${ico}</span>${label}</button>`).join('');el.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>go(b.dataset.go));}
  async function go(page){state.page=page;document.querySelectorAll('.page').forEach(p=>p.classList.toggle('active',p.dataset.page===page));document.getElementById('pageTitle').textContent=nav.find(x=>x[0]===page)?.[2]||page;renderNav();await renderPage(page)}
  const head=(k,h,p,a='')=>`<div class="page-head"><div><span class="eyebrow">${k}</span><h1>${h}</h1><p>${p}</p></div><div class="head-actions">${a}</div></div>`;
  const metric=(l,v,s)=>`<div class="card metric"><b>${l}</b><strong>${v}</strong><small>${s}</small></div>`;

  async function loadPermissions(){
    const uid=state.session.user.id;
    const [{data:profiles,error:pErr},{data:urs,error:uErr}]=await Promise.all([sb.from('aya_admin_users').select('*').eq('user_id',uid),sb.from('aya_admin_user_roles').select('role_id').eq('user_id',uid)]);
    if(pErr||uErr||!profiles?.[0]?.is_active)throw new Error('User ini bukan Admin AYA aktif.');
    const roleIds=(urs||[]).map(x=>x.role_id); if(!roleIds.length)throw new Error('Admin belum memiliki Role.');
    const {data:rfs,error:rErr}=await sb.from('aya_admin_role_functions').select('function_key').in('role_id',roleIds);if(rErr)throw rErr;
    state.functions=new Set((rfs||[]).map(x=>x.function_key));
  }

  async function renderDashboard(){
    const [t,o,b,c]=await Promise.all([
      can('testimonial.view')?sb.from('aya_testimonials').select('id',{count:'exact',head:true}).eq('status','pending'):Promise.resolve({count:0}),
      can('b2c.view')?sb.from('aya_orders').select('id',{count:'exact',head:true}):Promise.resolve({count:0}),
      can('b2b.view')?sb.from('aya_b2b_product_config').select('product_id',{count:'exact',head:true}).eq('supply_eligible',true):Promise.resolve({count:0}),
      can('website.view')?sb.from('aya_cms_slots').select('slot_key',{count:'exact',head:true}):Promise.resolve({count:0})
    ]);
    pageEl('dashboard').innerHTML=head('OPERATIONAL OVERVIEW','Yang perlu perhatian, dulu.','Exception-first workspace. Angka di bawah berasal dari database staging yang dapat diakses oleh role Anda.',chip('Live staging','good'))+
    `<div class="grid cols4">${metric('Pending Testimonials',t.count??0,'Menunggu moderation.')}${metric('B2C Orders',o.count??0,'Order foundation staging.')}${metric('B2B Eligible Products',b.count??0,'Explicit Product Master config.')}${metric('CMS Slots',c.count??0,'Draft / published content slots.')}</div>`+
    `<div class="section-title"><h2>Capability health</h2><span>truthful current state</span></div><div class="grid cols2"><div class="card pad"><div class="list"><div class="row"><div><b>Supabase</b><small>Auth + RLS + Admin DB connected.</small></div>${chip('Connected','good')}</div><div class="row"><div><b>Payment provider</b><small>Current public config remains disabled.</small></div>${chip('Inactive','warn')}</div><div class="row"><div><b>Shipping provider</b><small>Current public config remains disabled.</small></div>${chip('Inactive','warn')}</div></div></div><div class="card pad"><div class="list"><div class="row"><div><b>B2B core</b><small>Product config, measurements, economics and qualification foundation detected.</small></div>${chip('Available','good')}</div><div class="row"><div><b>Manual Mark Paid</b><small>Not assignable to human Admin.</small></div>${chip('Blocked by design','danger')}</div></div></div></div>`;
  }

  async function renderCms(){state.cms=await q('aya_cms_slots');const rows=state.cms.map(s=>`<tr><td><b>${esc(s.label)}</b><div class="muted-line">${esc(s.slot_key)}</div></td><td>${esc(s.area)}</td><td>${s.draft_version}</td><td>${s.published_version??'—'}</td><td>${s.published_at?chip('Published','good'):chip('Draft','warn')}</td><td><button class="btn ghost" data-cms="${esc(s.slot_key)}">Open</button></td></tr>`).join('');pageEl('cms').innerHTML=head('WEBSITE / CMS','Publikasi terkontrol, bukan page builder.','Content slots only. Product facts tetap di Product Master; Pasokan business logic bukan bagian CMS.',chip('Draft → Preview → Publish','blue'))+`<div class="table-wrap"><table><thead><tr><th>Slot</th><th>Area</th><th>Draft</th><th>Published</th><th>State</th><th></th></tr></thead><tbody>${rows}</tbody></table></div>`;pageEl('cms').querySelectorAll('[data-cms]').forEach(b=>b.onclick=()=>openCms(b.dataset.cms));}
  async function openCms(key){const s=state.cms.find(x=>x.slot_key===key);const text=s?.draft_content?.text??JSON.stringify(s?.draft_content??{},null,2);modal(`<h2>${esc(s.label)}</h2><div class="form-grid"><label class="full">Draft content<textarea id="cmsText">${esc(text)}</textarea></label><label class="full">Reason<input id="cmsReason" placeholder="Alasan perubahan"></label></div><div class="section-title"><h2>Published preview</h2><span>last public version</span></div><div class="preview-box">${esc(s?.published_content?.text??'Belum dipublikasikan.')}</div><div class="toolbar" style="margin-top:14px">${can('website.edit')?'<button id="cmsSave" class="btn">Save draft</button>':''}${can('website.publish')?'<button id="cmsPublish" class="btn primary">Publish</button>':''}${can('website.rollback')?'<button id="cmsHistory" class="btn ghost">Version history</button>':''}</div>`);if(document.getElementById('cmsSave'))document.getElementById('cmsSave').onclick=async()=>{try{const content={text:document.getElementById('cmsText').value};const reason=document.getElementById('cmsReason').value;const {error}=await sb.rpc('aya_admin_save_cms_draft',{p_slot_key:key,p_content:content,p_reason:reason||null});if(error)throw error;show('Draft tersimpan.','success');document.getElementById('modal').close();await renderCms()}catch(e){show(e.message,'error')}};if(document.getElementById('cmsPublish'))document.getElementById('cmsPublish').onclick=async()=>{try{const {error}=await sb.rpc('aya_admin_publish_cms_slot',{p_slot_key:key,p_reason:document.getElementById('cmsReason').value||null});if(error)throw error;show('Versi dipublikasikan.','success');document.getElementById('modal').close();await renderCms()}catch(e){show(e.message,'error')}};if(document.getElementById('cmsHistory'))document.getElementById('cmsHistory').onclick=()=>cmsHistory(key)}
  async function cmsHistory(key){const {data,error}=await sb.from('aya_cms_versions').select('*').eq('slot_key',key).order('created_at',{ascending:false});if(error)return show(error.message,'error');modal(`<h2>Version history</h2><div class="table-wrap"><table><thead><tr><th>Version</th><th>Status</th><th>Created</th><th></th></tr></thead><tbody>${(data||[]).map(v=>`<tr><td>${v.version}</td><td>${esc(v.version_status)}</td><td>${new Date(v.created_at).toLocaleString('id-ID')}</td><td><button class="btn ghost" data-rollback="${v.version}">Rollback</button></td></tr>`).join('')}</tbody></table></div>`);document.querySelectorAll('[data-rollback]').forEach(b=>b.onclick=async()=>{try{const {error:e}=await sb.rpc('aya_admin_rollback_cms_slot',{p_slot_key:key,p_version:Number(b.dataset.rollback),p_reason:'Admin rollback'});if(e)throw e;show('Rollback dipublikasikan sebagai versi baru.','success');document.getElementById('modal').close();await renderCms()}catch(e){show(e.message,'error')}})}

  async function renderProducts(){[state.products,state.variants,state.b2bConfig,state.measurements]=await Promise.all([q('aya_catalog_products'),q('aya_catalog_variants'),q('aya_b2b_product_config'),q('aya_b2b_measurements')]);const rows=state.products.map(p=>{const bc=state.b2bConfig.find(x=>x.product_id===p.product_id);return `<tr><td><b>${esc(p.product_name)}</b><div class="muted-line">${esc(p.product_id)}</div></td><td>${esc(p.line_name)}</td><td>${chip(p.public_status,p.public_status==='Tersedia'?'good':p.public_status==='Pre-order'?'warn':'danger')}</td><td>${p.orderable?chip('Orderable','good'):chip('Off')}</td><td>${state.variants.filter(v=>v.product_id===p.product_id).length}</td><td>${bc?.supply_eligible?chip('Bisa','blue'):chip('Tidak')}</td><td><button class="btn ghost" data-product="${esc(p.product_id)}">Edit</button></td></tr>`}).join('');pageEl('products').innerHTML=head('PRODUCT MASTER','Satu produk, dua commercial layers.','B2C public state dan B2B commercial config tetap dipisahkan. B2B eligibility eksplisit.',chip(`${state.products.length} products`,'good'))+`<div class="table-wrap"><table><thead><tr><th>Product</th><th>Line</th><th>Status</th><th>B2C</th><th>Variants</th><th>Pasokan</th><th></th></tr></thead><tbody>${rows}</tbody></table></div>`;pageEl('products').querySelectorAll('[data-product]').forEach(b=>b.onclick=()=>openProduct(b.dataset.product));}
  async function openProduct(id){const p=state.products.find(x=>x.product_id===id),vars=state.variants.filter(x=>x.product_id===id),bc=state.b2bConfig.find(x=>x.product_id===id),ms=state.measurements.filter(x=>x.product_id===id);modal(`<h2>${esc(p.product_name)}</h2><div class="form-grid"><label>Status<select id="pStatus"><option ${p.public_status==='Tersedia'?'selected':''}>Tersedia</option><option ${p.public_status==='Pre-order'?'selected':''}>Pre-order</option><option ${p.public_status==='Habis'?'selected':''}>Habis</option></select></label><label>B2C Orderable<select id="pOrder"><option value="true" ${p.orderable?'selected':''}>Ya</option><option value="false" ${!p.orderable?'selected':''}>Tidak</option></select></label><label>Visible<select id="pVisible"><option value="true" ${p.visible?'selected':''}>Ya</option><option value="false" ${!p.visible?'selected':''}>Tidak</option></select></label><label>Pasokan Usaha<select id="pSupply"><option value="true" ${bc?.supply_eligible?'selected':''}>Bisa</option><option value="false" ${!bc?.supply_eligible?'selected':''}>Tidak Bisa</option></select></label></div><div class="section-title"><h2>B2C variants</h2><span>current price</span></div><div class="list">${vars.map(v=>`<div class="row"><div><b>${esc(v.variant_name)}</b></div><strong>${money(v.unit_price)}</strong></div>`).join('')||'<div class="empty">No variants.</div>'}</div><div class="section-title"><h2>B2B measurements</h2><span>COGS internal</span></div><div class="list">${ms.map(m=>`<div class="row"><div><b>${esc(m.variant_name)} · ${esc(m.unit_label)}</b><small>Base cost ${money(m.base_cost)} · Final price ${money(m.final_unit_price)}</small></div><button class="btn ghost" data-measure="${m.id}">Economics</button></div>`).join('')||'<div class="empty">Belum ada measurement.</div>'}</div><div class="toolbar" style="margin-top:14px">${can('product.edit')?'<button id="saveProduct" class="btn primary">Save Product</button>':''}</div>`);if(document.getElementById('saveProduct'))document.getElementById('saveProduct').onclick=async()=>{try{const {error:e1}=await sb.from('aya_catalog_products').update({public_status:document.getElementById('pStatus').value,orderable:document.getElementById('pOrder').value==='true',visible:document.getElementById('pVisible').value==='true'}).eq('product_id',id);if(e1)throw e1;if(bc&&can('product.b2b.manage')){const {error:e2}=await sb.from('aya_b2b_product_config').update({supply_eligible:document.getElementById('pSupply').value==='true',updated_at:new Date().toISOString()}).eq('product_id',id);if(e2)throw e2}show('Product updated.','success');document.getElementById('modal').close();await renderProducts()}catch(e){show(e.message,'error')}};document.querySelectorAll('[data-measure]').forEach(b=>b.onclick=()=>openEconomics(b.dataset.measure))}
  async function openEconomics(id){const m=state.measurements.find(x=>x.id===id);const {data,error}=await sb.rpc('aya_b2b_measurement_economics_v1',{p_measurement_id:id});if(error)return show(error.message,'error');const e=data?.[0]||{};modal(`<h2>B2B Economics</h2><div class="grid cols2">${metric('COGS',money(e.cogs),'Base Cost + Additional Costs')}${metric('Recommended Unit Price',money(e.recommended_unit_price),'COGS + Rp5.000')}${metric('Supply Price',money(e.supply_price),'Final Unit Price − Rp2.000')}${metric('Margin',money(e.margin),e.margin_valid?'Valid (>0)':'BLOCK (≤0 / incomplete)')}</div><div class="form-grid" style="margin-top:16px"><label>Base Cost<input id="mCost" type="number" min="0" value="${m.base_cost??''}"></label><label>Final Unit Price<input id="mPrice" type="number" min="0" value="${m.final_unit_price??''}"></label></div><div class="toolbar" style="margin-top:14px">${can('b2b.cogs.edit')||can('b2b.unit_price.edit')?'<button id="saveEconomics" class="btn primary">Save</button>':''}</div>`);if(document.getElementById('saveEconomics'))document.getElementById('saveEconomics').onclick=async()=>{try{const patch={};if(can('b2b.cogs.edit'))patch.base_cost=document.getElementById('mCost').value===''?null:Number(document.getElementById('mCost').value);if(can('b2b.unit_price.edit'))patch.final_unit_price=document.getElementById('mPrice').value===''?null:Number(document.getElementById('mPrice').value);patch.updated_at=new Date().toISOString();const {error:e2}=await sb.from('aya_b2b_measurements').update(patch).eq('id',id);if(e2)throw e2;show('B2B economics input updated; commercial readiness tetap dihitung backend.','success');document.getElementById('modal').close();await renderProducts()}catch(e){show(e.message,'error')}}}

  async function renderB2c(){const {data,error}=await sb.from('aya_orders').select('*').order('submitted_at',{ascending:false}).limit(100);if(error)throw error;state.orders=data||[];pageEl('b2c').innerHTML=head('B2C OPERATIONS','Pesanan sekali beli tetap satu domain.','Belanja biasa dan acara satu kali tidak berubah menjadi B2B karena quantity.',window.AYA_CONFIG.checkout?.orderPersistence?chip('Persistence ON','good'):chip('Persistence OFF','warn'))+`<div class="table-wrap"><table><thead><tr><th>Order</th><th>Customer</th><th>Context</th><th>Subtotal</th><th>Order State</th><th>Payment</th><th></th></tr></thead><tbody>${state.orders.map(o=>`<tr><td>${esc(o.order_number)}</td><td>${esc(o.customer_name)}</td><td>${esc(o.context)}</td><td>${money(o.subtotal_amount)}</td><td>${chip(o.order_status,'blue')}</td><td>${chip(o.payment_status,o.payment_status==='paid'?'good':o.payment_status==='pending'?'warn':'')}</td><td><button class="btn ghost" data-order="${o.id}">Inspect</button></td></tr>`).join('')||'<tr><td colspan="7">No persisted B2C orders.</td></tr>'}</tbody></table></div>`;pageEl('b2c').querySelectorAll('[data-order]').forEach(b=>b.onclick=()=>openOrder(b.dataset.order));}
  async function openOrder(id){const o=state.orders.find(x=>x.id===id);const {data:items}=await sb.from('aya_order_items').select('*').eq('order_id',id).order('line_number');modal(`<h2>${esc(o.order_number)}</h2><div class="grid cols3">${metric('Subtotal',money(o.subtotal_amount),'Snapshot')}${metric('Shipping',money(o.shipping_amount),'May be pending')}${metric('Total',money(o.total_amount),'May be pending')}</div><div class="section-title"><h2>Items</h2></div><div class="list">${(items||[]).map(i=>`<div class="row"><div><b>${esc(i.product_name_snapshot)}</b><small>${esc(i.variant_name_snapshot)} · ${i.quantity} pcs</small></div><strong>${money(i.item_subtotal)}</strong></div>`).join('')}</div><div class="section-title"><h2>Operational state</h2><span>Payment state is read-only</span></div><div class="form-grid"><label>Order status<select id="orderState">${['received','reviewing','confirmed','cancelled','archived'].map(s=>`<option ${o.order_status===s?'selected':''}>${s}</option>`).join('')}</select></label><label>Payment status<input value="${esc(o.payment_status)}" disabled></label></div>${can('b2c.order.status.edit')?'<div class="toolbar" style="margin-top:14px"><button id="saveOrder" class="btn primary">Save operational state</button></div>':''}`);if(document.getElementById('saveOrder'))document.getElementById('saveOrder').onclick=async()=>{try{const {error}=await sb.from('aya_orders').update({order_status:document.getElementById('orderState').value,updated_at:new Date().toISOString()}).eq('id',id);if(error)throw error;show('Order operational state updated.','success');document.getElementById('modal').close();await renderB2c()}catch(e){show(e.message,'error')}}}

  async function renderB2b(){const [cfgs,ms,ths,settings]=await Promise.all([q('aya_b2b_product_config'),q('aya_b2b_measurements'),q('aya_b2b_qualification_thresholds'),q('aya_b2b_qualification_settings')]);state.b2bConfig=cfgs;state.measurements=ms;pageEl('b2b').innerHTML=head('B2B OPERATIONS','Admin menangani konfigurasi dan pengecualian.','Qualification happy path dan economics calculation tetap system-driven.',settings[0]?.qualification_enabled?chip('Qualification ON','good'):chip('Qualification OFF','warn'))+`<div class="grid cols4">${metric('Eligible Products',cfgs.filter(x=>x.supply_eligible).length,'Explicit Product Master config')}${metric('Measurements',ms.length,'Commercial measurements')}${metric('Commercial Enabled',ms.filter(x=>x.commercial_enabled).length,'Still subject to backend margin guard')}${metric('Rule Version',settings[0]?.active_rule_version||'—','W1 / W2 / M1 / M2')}</div><div class="section-title"><h2>Qualification thresholds</h2><span>canonical backend table</span></div><div class="table-wrap"><table><thead><tr><th>Class</th><th>Cadence</th><th>Minimum</th><th>Rule</th></tr></thead><tbody>${ths.map(t=>`<tr><td>${esc(t.product_class)}</td><td>${esc(t.cadence)}</td><td>${t.minimum_quantity_kg!=null?`${t.minimum_quantity_kg} kg`:money(t.minimum_value)}</td><td>${esc(t.rule_version)}</td></tr>`).join('')}</tbody></table></div><div class="section-title"><h2>Commercial measurements</h2><span>COGS is internal-only</span></div><div class="table-wrap"><table><thead><tr><th>Product</th><th>Variant</th><th>Unit</th><th>Base Cost</th><th>Final Unit Price</th><th>Enabled</th><th></th></tr></thead><tbody>${ms.map(m=>`<tr><td>${esc(m.product_id)}</td><td>${esc(m.variant_name)}</td><td>${esc(m.unit_label)}</td><td>${money(m.base_cost)}</td><td>${money(m.final_unit_price)}</td><td>${m.commercial_enabled?chip('Yes','good'):chip('No')}</td><td><button class="btn ghost" data-b2becon="${m.id}">Economics</button></td></tr>`).join('')}</tbody></table></div>`;pageEl('b2b').querySelectorAll('[data-b2becon]').forEach(b=>b.onclick=()=>openEconomics(b.dataset.b2becon));}

  async function renderTestimonials(){const {data,error}=await sb.from('aya_testimonials').select('*').order('submitted_at',{ascending:false});if(error)throw error;state.testimonials=data||[];pageEl('testimonials').innerHTML=head('TESTIMONIALS','Moderate dulu. Publish kemudian.','Approve/Reject dipisahkan dari Publish/Unpublish. Original submission tidak ditimpa.',chip(`${state.testimonials.length} submissions`,'good'))+`<div class="table-wrap"><table><thead><tr><th>Name</th><th>Product</th><th>Format</th><th>Status</th><th>Public</th><th>Submitted</th><th></th></tr></thead><tbody>${state.testimonials.map(t=>`<tr><td>${esc(t.display_name)}</td><td>${esc(t.product_name_snapshot)}</td><td>${esc(t.testimonial_format)}</td><td>${chip(t.status,t.status==='approved'?'good':t.status==='rejected'?'danger':'warn')}</td><td>${t.is_featured?chip('Published','good'):chip('Not public')}</td><td>${new Date(t.submitted_at).toLocaleDateString('id-ID')}</td><td><button class="btn ghost" data-testimonial="${t.id}">Review</button></td></tr>`).join('')}</tbody></table></div>`;pageEl('testimonials').querySelectorAll('[data-testimonial]').forEach(b=>b.onclick=()=>openTestimonial(b.dataset.testimonial));}
  function openTestimonial(id){const t=state.testimonials.find(x=>x.id===id);modal(`<h2>${esc(t.display_name)}</h2><p class="muted">${esc(t.product_name_snapshot)} · ${esc(t.testimonial_format)} · ${esc(t.city||'')}</p><div class="preview-box">${esc(t.testimonial_text)}</div><div class="form-grid" style="margin-top:14px"><label>Public text<textarea id="tText">${esc(t.approved_text||t.testimonial_text)}</textarea></label><label>Public identity<textarea id="tIdentity">${esc(t.public_display_name||t.display_name)}${t.public_city||t.city?'\n'+esc(t.public_city||t.city):''}</textarea></label><label class="full">Rejection note<input id="tReject" value="${esc(t.rejection_note||'')}"></label></div><div class="toolbar" style="margin-top:14px">${can('testimonial.moderate')?'<button id="tApprove" class="btn primary">Approve</button><button id="tRejectBtn" class="btn danger">Reject</button>':''}${can('testimonial.publish')&&t.status==='approved'?`<button id="tPublish" class="btn">${t.is_featured?'Unpublish':'Publish'}</button>`:''}</div>`);const identity=()=>{const [name,...city]=document.getElementById('tIdentity').value.split('\n');return{name:name.trim(),city:city.join(' ').trim()||null}};if(document.getElementById('tApprove'))document.getElementById('tApprove').onclick=async()=>{try{const i=identity();const {error}=await sb.rpc('aya_admin_moderate_testimonial',{p_id:id,p_decision:'approved',p_approved_text:document.getElementById('tText').value,p_public_name:i.name,p_public_city:i.city,p_rejection_note:null});if(error)throw error;show('Testimonial approved.','success');document.getElementById('modal').close();await renderTestimonials()}catch(e){show(e.message,'error')}};if(document.getElementById('tRejectBtn'))document.getElementById('tRejectBtn').onclick=async()=>{try{const {error}=await sb.rpc('aya_admin_moderate_testimonial',{p_id:id,p_decision:'rejected',p_approved_text:null,p_public_name:null,p_public_city:null,p_rejection_note:document.getElementById('tReject').value||'Tidak disetujui'});if(error)throw error;show('Testimonial rejected.','success');document.getElementById('modal').close();await renderTestimonials()}catch(e){show(e.message,'error')}};if(document.getElementById('tPublish'))document.getElementById('tPublish').onclick=async()=>{try{const {error}=await sb.rpc('aya_admin_set_testimonial_publication',{p_id:id,p_publish:!t.is_featured,p_display_order:t.display_order,p_public_media_url:null});if(error)throw error;show(t.is_featured?'Testimonial unpublished.':'Testimonial published.','success');document.getElementById('modal').close();await renderTestimonials()}catch(e){show(e.message,'error')}}}

  async function renderFinance(){pageEl('finance').innerHTML=head('FINANCE / PAYMENT','Paid bukan Settled.','Invoice, Payment, Settlement, Credit, Refund dan Reconciliation adalah entity terpisah.',window.AYA_CONFIG.payment?.enabled?chip('Provider enabled','good'):chip('Provider inactive','warn'))+`<div class="grid cols3">${metric('Payment Provider','Inactive','DOKU primary / Midtrans fallback is target architecture.')}${metric('Manual Mark Paid','Unavailable','System-only authority; no human permission exists.')}${metric('Settlement','Not active','No provider settlement feed is connected yet.')}</div><div class="section-title"><h2>Finance domains</h2><span>ready UI boundaries</span></div><div class="card pad"><div class="provider-line"><div><b>Invoices</b><small>Requires invoice backend entities before live records can appear.</small></div>${chip('Dependency pending','warn')}</div><div class="provider-line"><div><b>Payments</b><small>Verified payment must come from trusted backend/provider.</small></div>${chip('Provider inactive','warn')}</div><div class="provider-line"><div><b>Settlements</b><small>Paid customer state remains independent from settlement delay.</small></div>${chip('Provider inactive','warn')}</div><div class="provider-line"><div><b>Kredit Pasokan / Refunds</b><small>UI boundary reserved; no fake ledger values are created.</small></div>${chip('Backend dependency','warn')}</div></div>`}

  async function renderAccess(){const [funcs,roles,urs]=await Promise.all([q('aya_admin_functions'),q('aya_admin_roles'),q('aya_admin_user_roles')]);state.roles=roles;state.userRoles=urs;pageEl('access').innerHTML=head('USERS & ACCESS','Functions → Roles → Admin Users.','Effective permissions adalah union dari Roles. System-only functions tidak assignable.',chip(`${funcs.filter(f=>!f.system_only).length} assignable functions`,'good'))+`<div class="grid cols2"><div class="card pad"><div class="section-title" style="margin-top:0"><h2>Roles</h2></div><div class="list">${roles.map(r=>`<div class="row"><div><b>${esc(r.role_name)}</b><small>${esc(r.description||'')}</small></div>${r.is_system?chip('System role','blue'):chip('Custom')}</div>`).join('')}</div></div><div class="card pad"><div class="section-title" style="margin-top:0"><h2>Function Registry</h2></div><div class="perm-grid">${funcs.slice(0,60).map(f=>`<div class="perm"><code>${esc(f.function_key)}</code><small>${esc(f.label)}${f.system_only?' · system-only':''}</small></div>`).join('')}</div></div></div>`}

  async function renderAudit(){const {data,error}=await sb.from('aya_admin_audit_log').select('*').order('created_at',{ascending:false}).limit(200);if(error)throw error;state.audit=data||[];pageEl('audit').innerHTML=head('AUDIT','Siapa mengubah apa, dengan fungsi apa.','Audit history bersifat append-only untuk Admin biasa.',chip(`${state.audit.length} recent events`,'good'))+`<div class="table-wrap"><table><thead><tr><th>Time</th><th>Function</th><th>Entity</th><th>Action</th><th>Reason</th><th>Reference</th></tr></thead><tbody>${state.audit.map(a=>`<tr><td>${new Date(a.created_at).toLocaleString('id-ID')}</td><td><code>${esc(a.effective_function||'')}</code></td><td>${esc(a.entity_type)} · ${esc(a.entity_id||'')}</td><td>${esc(a.action)}</td><td>${esc(a.reason||'')}</td><td>${esc(a.reference||'')}</td></tr>`).join('')||'<tr><td colspan="6">No admin audit events yet.</td></tr>'}</tbody></table></div>`}

  async function renderSystem(){const [settings]=await Promise.all([q('aya_b2b_qualification_settings')]);pageEl('system').innerHTML=head('SYSTEM','Capability health dan rule versions.','Technical failures dan business exceptions tetap queue terpisah.',chip('Staging','blue'))+`<div class="card pad"><div class="provider-line"><div><b>Supabase Auth / RLS</b><small>Admin session + atomic permission registry active.</small></div>${chip('Healthy','good')}</div><div class="provider-line"><div><b>B2B qualification engine</b><small>Rule ${esc(settings[0]?.active_rule_version||'—')} · enabled=${String(settings[0]?.qualification_enabled??false)}</small></div>${settings[0]?.qualification_enabled?chip('Enabled','good'):chip('Disabled','warn')}</div><div class="provider-line"><div><b>Payment adapter</b><small>Current AYA_CONFIG.payment.enabled=${String(window.AYA_CONFIG.payment?.enabled)}</small></div>${chip('Inactive','warn')}</div><div class="provider-line"><div><b>Shipping adapter</b><small>Current AYA_CONFIG.shipping.enabled=${String(window.AYA_CONFIG.shipping?.enabled)}</small></div>${chip('Inactive','warn')}</div><div class="provider-line"><div><b>Admin media bucket</b><small>Private storage bucket with permission-scoped RLS.</small></div>${chip('Configured','good')}</div></div>`}

  async function renderPage(page){try{if(page==='dashboard')return renderDashboard();if(page==='cms')return renderCms();if(page==='products')return renderProducts();if(page==='b2c')return renderB2c();if(page==='b2b')return renderB2b();if(page==='testimonials')return renderTestimonials();if(page==='finance')return renderFinance();if(page==='access')return renderAccess();if(page==='audit')return renderAudit();if(page==='system')return renderSystem()}catch(e){pageEl(page).innerHTML=head('ERROR','Data belum dapat dimuat.',e.message,chip('Error','danger'));}}

  async function boot(session){state.session=session;if(!session){document.getElementById('loginView').hidden=false;document.getElementById('appView').hidden=true;return}try{await loadPermissions();document.getElementById('loginView').hidden=true;document.getElementById('appView').hidden=false;document.getElementById('sessionLabel').textContent=session.user.email||'Admin';renderNav();const first=nav.find(x=>can(x[3]))?.[0]||'dashboard';await go(first)}catch(e){await sb.auth.signOut();document.getElementById('loginError').textContent=e.message}}

  document.getElementById('loginForm').onsubmit=async(e)=>{e.preventDefault();const err=document.getElementById('loginError');err.textContent='';const {data,error}=await sb.auth.signInWithPassword({email:document.getElementById('loginEmail').value.trim(),password:document.getElementById('loginPassword').value});if(error)return err.textContent=error.message;await boot(data.session)};
  document.getElementById('logoutBtn').onclick=async()=>{await sb.auth.signOut();location.reload()};
  document.getElementById('refreshBtn').onclick=()=>renderPage(state.page);
  sb.auth.onAuthStateChange((_e,s)=>{if((_e==='SIGNED_OUT'||_e==='SIGNED_IN')&&s!==state.session)boot(s)});
  sb.auth.getSession().then(({data})=>boot(data.session));
})();
