(()=>{
'use strict';
const cfg=window.AYA_CONFIG?.supabase||{};
if(!window.supabase?.createClient||!cfg.url||!cfg.publishableKey)return;
const sb=window.supabase.createClient(cfg.url,cfg.publishableKey,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
window.AYA_ADMIN_AUTH=sb;
const $=id=>document.getElementById(id);
const show=view=>{const login=$('loginView'),reset=$('resetView'),app=$('appView');if(login)login.hidden=view!=='login';if(reset)reset.hidden=view!=='reset';if(app)app.hidden=view!=='app';};
const message=(id,text,type='error')=>{const el=$(id);if(!el)return;el.textContent=text||'';el.className=`form-error ${type}`;};
const classify=e=>{const m=String(e?.message||e||'');if(/invalid api key/i.test(m))return 'Konfigurasi Supabase tidak valid. Periksa URL dan publishable key.';if(/invalid login credentials|invalid password/i.test(m))return 'Email atau password salah.';if(/network|fetch|failed to fetch/i.test(m))return 'Tidak dapat terhubung ke Supabase.';return m||'Login gagal. Silakan coba lagi.';};
async function verifyAdmin(session){const{data,error}=await sb.from('aya_admin_users').select('id,email,is_active').eq('auth_user_id',session.user.id).maybeSingle();if(error)throw error;if(!data)return{ok:false,msg:'Akun berhasil login, tetapi belum terdaftar sebagai Admin AYA.'};if(!data.is_active)return{ok:false,msg:'Akun Admin tidak aktif.'};return{ok:true,user:data};}
async function enter(session){if(!session){show('login');return;}try{const v=await verifyAdmin(session);if(!v.ok){await sb.auth.signOut();show('login');message('loginError',v.msg);return;}window.AYA_ADMIN_USER=v.user;show('app');window.dispatchEvent(new CustomEvent('aya:admin-auth-ready',{detail:{session,adminUser:v.user}}));}catch(e){await sb.auth.signOut();show('login');message('loginError',`Admin access gagal diverifikasi: ${classify(e)}`);}}
async function init(){const recovery=window.location.hash.includes('type=recovery');if(recovery)show('reset');const{data}=await sb.auth.getSession();if(data?.session&&!recovery)await enter(data.session);else if(!recovery)show('login');
$('loginForm')?.addEventListener('submit',async event=>{event.preventDefault();message('loginError','');const email=$('loginEmail')?.value.trim()||'';const password=$('loginPassword')?.value||'';if(!email||!password){message('loginError','Email dan password wajib diisi.');return;}const btn=$('loginForm')?.querySelector('button[type="submit"]');if(btn)btn.disabled=true;try{const{data,error}=await sb.auth.signInWithPassword({email,password});if(error)throw error;await enter(data.session);}catch(e){message('loginError',classify(e));}finally{if(btn)btn.disabled=false;}});
$('forgotPasswordBtn')?.addEventListener('click',async()=>{const email=$('loginEmail')?.value.trim();message('loginError','');if(!email){message('loginError','Masukkan email Admin terlebih dahulu.');$('loginEmail')?.focus();return;}const redirectTo=`${window.location.origin}/admin/`;const{error}=await sb.auth.resetPasswordForEmail(email,{redirectTo});if(error)message('loginError',classify(error));else message('loginError','Jika email terdaftar, instruksi reset password telah dikirim.','success');});
$('resetForm')?.addEventListener('submit',async event=>{event.preventDefault();message('resetError','');const password=$('newPassword')?.value||'',confirmation=$('confirmPassword')?.value||'';if(password.length<8)return message('resetError','Password minimal 8 karakter.');if(password!==confirmation)return message('resetError','Konfirmasi password tidak sama.');const{error}=await sb.auth.updateUser({password});if(error)return message('resetError',classify(error));window.history.replaceState({},document.title,`${window.location.pathname}${window.location.search}`);show('login');message('loginError','Password berhasil diperbarui. Silakan login kembali.','success');});
sb.auth.onAuthStateChange((event,session)=>{if(event==='PASSWORD_RECOVERY')show('reset');else if(event==='SIGNED_OUT')show('login');});}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();